services:
  - postgresql
addons:
    postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user socializa password 'socializa'"
  - psql -U postgres -c "create database test_socializa owner socializa"
  - psql -U postgres -d test_socializa -c "create extension postgis"
language: python
python:
  - "3.4"
install:
  - pip install -r backend/requirements.txt
  - pip install coveralls
script:
  - cd backend
  - python manage.py test --keepdb
  - coverage run --source='.' manage.py test --keepdb
after_success: coveralls
