services:
  - postgresql
addons:
    postgresql: "9.4"
before_script:
  - psql -c 'create database socializa_test;' -U socializa
  - psql -U socializa -c "create extension postgis"
language: python
python:
  - "3.4"
install:
  - pip install -r backend/requirements.txt
  - pip install coveralls
script:
  - cd backend
  - python manage.py migrate
  - python manage.py test --keepdb
  - coverage run --source='.' manage.py test --keepdb
after_success: coveralls
